# Generated by Django 5.2.2 on 2026-04-27 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=6, unique=True)),
                ('max_graczy', models.IntegerField(default=6)),
                ('min_punkty', models.IntegerField(default=100)),
                ('aktywna', models.BooleanField(default=True)),
                ('stworzona', models.DateTimeField(auto_now_add=True)),
                ('gracze', models.ManyToManyField(blank=True, related_name='rooms', to='accounts.player')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to='accounts.player')),
            ],
        ),
    ]
