# Generated by Django 5.2.2 on 2026-05-25 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stan_json', models.TextField()),
                ('zaktualizowano', models.DateTimeField(auto_now=True)),
                ('pokoj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_state', to='lobby.room')),
            ],
        ),
    ]
